info_penyakit = {
    "Refluks (GERD)": {
        "deskripsi": "Gastroesophageal Reflux Disease (GERD) adalah kondisi patologis atau gangguan pencernaan kronis di mana asam lambung dan isi lambung naik kembali ke esofagus (kerongkongan). Hal ini terjadi akibat melemahnya katup Lower Esophageal Sphincter (LES). Kondisi ini menimbulkan gejala khas seperti rasa panas atau terbakar di dada (heartburn), regurgitasi, nyeri dada yang kadang mirip serangan jantung, hingga batuk kronis dan ketidaknyamanan saat malam hari.",
        "saran": "Pengobatan GERD dapat dilakukan dengan terapi farmakologis, di mana penggunaan obat golongan Proton Pump Inhibitor (PPI) sering dijadikan sebagai terapi lini pertama. Karena gejalanya bisa menyerupai penyakit jantung, sangat penting untuk berkonsultasi dengan dokter. Selain itu, perbaiki pola tidur karena gangguan tidur dan GERD memiliki hubungan dua arah yang saling memperparah.",
        "pencegahan": "Kunci utama pencegahannya adalah modifikasi gaya hidup. Jaga berat badan ideal atau indeks massa tubuh (BMI) normal. Hindari faktor pemicu seperti makanan pedas, berlemak, kafein, dan alkohol. Berhenti merokok, kelola tingkat stres dengan baik, serta hindari langsung berbaring setelah makan.",
        "referensi": "[1] Sangging, P. R. A., dkk. (2025). Penyakit GERD. MEDIC NUTRICIA: Jurnal Ilmu Kesehatan, Vol. 16 No. 2.\n[2] Putri, A. K. Z., dkk. (2023). Modifikasi Gaya Hidup Dan Kajian Pengobatan Pada Penderita Gastroesophageal Reflux Disease (GERD). Scientific Journal of Nursing.\n[3] Rahmadani, T. S., dkk. (2026). Hubungan Dua Arah Antara Gastroesophageal Reflux Disease dengan Gangguan Tidur. Medula, Vol. 16, No. 1.\n[4] Indriastuti, D., dkk. (2024). Penyuluhan Kesehatan Mengenai Pengenalan Gangguan Kesehatan Pencernaan: Gastroesophageal Reflux Disease (GERD) Dan Penanganannya. Karya Kesehatan Journal of Community Engagement, Vol. 05, No. 02.\n[5] Kuncoro, D., dkk. (2024). Jaringan Syaraf Tiruan Memprediksi Penyakit Gerd. Bridge: Jurnal Publikasi Sistem Informasi dan Telekomunikasi, Vol. 2 No. 4."
    },
    "Infeksi Saluran Pencernaan (Colera)": {
        "deskripsi": "Kolera adalah penyakit infeksi usus akut yang disebabkan oleh bakteri Vibrio cholerae. Penyakit ini menular melalui rute fekal-oral, yakni melalui konsumsi air atau makanan yang terkontaminasi kotoran penderita. Gejala khas kolera meliputi diare encer yang berlimpah (tinja berubah menjadi cairan putih keruh menyerupai air cucian beras tanpa bau busuk), muntah yang timbul setelah diare, hingga kejang otot. Kondisi ini dapat menyebabkan pasien kehilangan cairan secara cepat dan berujung pada dehidrasi berat, syok, hingga kematian jika tidak segera ditangani.",
        "saran": "Penanganan paling utama dan krusial untuk pasien kolera adalah terapi rehidrasi untuk mengganti cairan dan elektrolit tubuh yang hilang secara cepat. Pada kasus ringan hingga sedang, berikan larutan oralit (Oral Rehydration Salts/ORS). Namun, pada kasus dengan tingkat dehidrasi berat, pasien harus segera dilarikan ke rumah sakit untuk mendapatkan rehidrasi intravena (infus) dan pemberian antibiotik sesuai indikasi medis guna mempercepat penyembuhan dan menghentikan penularan.",
        "pencegahan": "Pencegahan kolera sangat bergantung pada perbaikan kualitas sanitasi lingkungan dan penerapan Perilaku Hidup Bersih dan Sehat (PHBS). Selalu pastikan untuk mengonsumsi air yang sudah direbus hingga mendidih, mencuci tangan dengan sabun sebelum makan dan setelah buang air, serta menghindari konsumsi makanan laut atau sayuran mentah yang tidak diolah dengan baik. Selain itu, pemberian vaksinasi kolera oral juga sangat direkomendasikan sebagai upaya perlindungan tambahan.",
        "referensi": "[1] Panjaitan, Z., dkk. (2022). Aplikasi Sistem Pakar Untuk Mendiagnosa Lebih Dini Penyakit Kolera Pada Anak Menggunakan Metode K-Nearest Neighbor (KNN). Journal of Science and Social Research, V(2): 220-229.\n[2] Marasi, J. H. S., dkk. (2024). Pengaruh Kebersihan Lingkungan dan Sanitasi Terhadap Penyakit Menular Kolera. Integrative Perspectives of Social and Science Journal (IPSSJ), Vol 2 No.3, hlm. 4013-4021.\n[3] Ramdhaniah, E. N., dkk. (2021). Dampak Penanganan Epidemi Kolera Terhadap Kondisi Sosial Budaya Penduduk Batavia Tahun 1900-1920. Historiography: Journal of Indonesian History and Education, Vol.1 No.3, hlm. 284-301.\n[4] Nuha, A. R., dkk. (2025). Strategi Pengendalian Penyebaran Penyakit Kolera dengan Vaksinasi, Edukasi, dan Karantina: Analisis Model dan Simulasi. Mandalika Mathematics and Education Journal, Vol 7 No.4, hlm. 2101-2118.\n[5] Rauf, T. C. I., & Prawoto, B. P. (2023). Dinamika Penyebaran Penyakit Kolera Dengan Adanya Vaksinasi. Jurnal Silogisme: Kajian Ilmu Matematika dan Pembelajarannya, Vol 8 No.1, hlm. 56-66."
    },
    "Maag (Dispepsia)": {
        "deskripsi": "Dispepsia (yang di masyarakat umum sering dikenal sebagai penyakit maag) merupakan suatu sindrom atau kumpulan gejala klinis yang ditandai dengan rasa nyeri, panas, atau tidak nyaman pada perut bagian atas (ulu hati). Kondisi ini diklasifikasikan menjadi dua, yaitu dispepsia organik (terdapat kelainan anatomis pada saluran cerna) dan dispepsia fungsional (tidak ditemukan kelainan struktural). Gejala penyertanya sering kali meliputi perut kembung, mual, cepat merasa kenyang saat makan, dan sering bersendawa.",
        "saran": "Penanganan utama untuk sindrom dispepsia meliputi kombinasi terapi farmakologis dan non-farmakologis. Terapi medis biasanya menggunakan obat pereda asam lambung seperti antasida, penghambat pompa proton (PPI), atau prokinetik sesuai dengan resep dokter. Selain itu, penderita sangat disarankan untuk melakukan manajemen stres dengan baik (coping stress), karena faktor psikologis dan stres yang tinggi terbukti secara klinis dapat memicu kekambuhan dispepsia fungsional.",
        "pencegahan": "Pencegahan paling efektif adalah dengan memodifikasi gaya hidup dan menjaga kedisiplinan pola makan. Biasakan makan dengan porsi kecil namun sering, dan sangat dianjurkan untuk tidak melewatkan sarapan pagi. Hindari makanan dan minuman yang dapat mengiritasi mukosa lambung, seperti makanan yang terlalu pedas, asam, berlemak tinggi, serta batasi konsumsi kopi (kafein), teh pekat, minuman bersoda, dan alkohol.",
        "referensi": "[1] Zakiyah, W., dkk. (2021). Definisi, Penyebab, Klasifikasi, dan Terapi Sindrom Dispepsia. Jurnal Health Sains, Vol. 2 No. 7.\n[2] Saputri, S. A., dkk. (2025). Analisis Kejadian Dispepsia terhadap Faktor Pemicunya. BIOCITY Journal of Pharmacy Bioscience and Clinical Community, 3(2): 69-84.\n[3] Puteri, A. D., & Yuristin, D. (2022). Hubungan Tidak Sarapan Pagi, Jenis Makanan dan Minuman yang Memicu Asam Lambung dengan Kejadian Dispepsia pada Remaja. KOLONI: Jurnal Multidisiplin Ilmu, 1(2): 666-674.\n[4] Timah, S. (2021). Hubungan Pola Makan Pada Pasien Dispepsia. Jurnal Ilmiah Kesehatan Diagnosis, Vol. 16 No. 1.\n[5] Martin, A., dkk. (2024). Kegiatan Pengabdian Masyarakat dalam Rangka Edukasi Masyarakat Mengenai Penapisan GERD dan Dispepsia pada Lanjut Usia. Jurnal Pengabdian Bidang Kesehatan, Vol. 2 No. 4, Hal 16-22."
    },
    "Radang Hati (Hepatitis)": {
        "deskripsi": "Hepatitis adalah penyakit peradangan pada organ hati (liver) manusia yang umumnya disebabkan oleh infeksi virus (seperti Hepatitis A, B, C, D, dan E), namun juga bisa dipicu oleh gaya hidup tidak sehat, konsumsi alkohol, atau autoimun. Penyakit ini sering kali tidak menunjukkan gejala berat di awal, tetapi dapat sangat menular (tergantung jenis virusnya) dan berpotensi mematikan jika berkembang menjadi sirosis atau kanker hati. Gejala umum yang sering muncul meliputi tubuh terasa lemas, mual, urin berwarna gelap, hingga warna mata dan kulit menjadi kekuningan (jaundice).",
        "saran": "Jika dicurigai mengalami gejala hepatitis, sangat diwajibkan untuk segera melakukan pemeriksaan medis secara langsung, terutama tes darah (seperti cek kadar SGOT, SGPT, dan bilirubin) untuk memastikan jenis dan tingkat keparahannya. Pengobatan harus di bawah pengawasan dokter, yang mungkin meliputi terapi obat antivirus (untuk infeksi kronis) atau perawatan suportif. Pasien diwajibkan untuk istirahat total (bed rest) dan dilarang keras mengonsumsi alkohol maupun obat bebas yang dapat memperberat kerja organ hati.",
        "pencegahan": "Tindakan pencegahan paling efektif dan utama adalah melalui pemberian vaksinasi, khususnya untuk Hepatitis A dan Hepatitis B. Selain itu, terapkan gaya hidup bersih dan sehat (PHBS), pastikan kematangan dan kebersihan makanan/minuman, serta hindari praktik berisiko tinggi seperti berbagi barang kebersihan pribadi (sikat gigi, pisau cukur) dan penggunaan jarum suntik secara bergantian untuk memutus rantai penularan.",
        "referensi": "[1] Putra, A. D., dkk. (2024). Supervised Machine Learning Model untuk Prediksi Penyakit Hepatitis. Indonesian Journal of Computer Science, 13(2).\n[2] Tjen, J., & Pratama, V. (2023). Penentuan Jalur Diagnostik Penyakit Berbasis Konsep Pembelajaran Mesin: Studi kasus Penyakit Hepatitis C. Journal of Applied Computer Science and Technology (JACOST), 4(2), 124-130.\n[3] Riyanto, I. R., dkk. (2021). Diagnosa Penyakit Hepatitis Menggunakan Metode Sorensen Coefficient. Jurnal Teknik Informatika dan Sistem Informasi, 8(3), 1307-1321.\n[4] Nugroho, R. E., dkk. (2024). Pendeteksi Penyakit Hepatitis Menggunakan CART Decision Tree. JITET (Jurnal Informatika dan Teknik Elektro Terapan), 12(3S1).\n[5] Syahputra, H., & Syafindy, D. M. (2023). Sistem Pakar Diagnosa Penyakit Hepatitis Dengan Menggunakan Metode Certainty Factor. Jurnal Sains Informatika Terapan (JSIT), 2(1), 45-50."
    },
    "Radang Usus Buntu (Apendisitis)": {
        "deskripsi": "Apendisitis secara umum adalah peradangan akibat infeksi pada usus buntu atau umbai cacing (apendiks). Gejala penyakit usus buntu umumnya berupa nyeri pada perut kanan bawah, demam, hingga mual dan muntah. Dari berbagai penelitian yang telah dilakukan, obstruksi merupakan penyebab yang dominan dan merupakan pencetus untuk terjadinya apendisitis.",
        "saran": "Jika sudah terjadi peradangan, tindakan yang biasanya dilakukan adalah dengan operasi pengangkatan usus buntu. Setelah operasi, pasien perlu melakukan penyesuaian pola makan sebelum kembali ke pola makan normal. Semakin positif sikap pasien dalam menghadapi pengelolaan apendisitis, maka semakin baik praktik pasien dalam mencegah komplikasi lebih serius.",
        "pencegahan": "Hindari faktor risiko potensial seperti diet rendah serat dan tinggi gula. Sangat penting untuk mengkonsumsi makanan yang mengandung serat secara rutin agar mudah dicerna oleh sistem pencernaan, serta menghindari makanan yang terlalu pedas.",
        "referensi": "[1] Apriliani, E., Zaini, S., & Kapadia, R. (2022). Hubungan Tingkat Pengetahuan Terhadap Kepatuhan Diit Pada Pasien Apendisitis di Poli Bedah RSUD dr. Abdul Azis Singkawang Tahun 2019. Scientific Journal of Nursing Research, Vol 4 No 2, hlm. 63-67."
    },
    "Gangguan Pencernaan (Disentry)": {
        "deskripsi": "Disentri adalah infeksi yang menimbulkan luka dan tukak yang terbatas pada kolon (usus besar). Penyakit ini ditandai dengan gejala khas yang dikenal sebagai sindrom disentri, yaitu sakit perut yang sering disertai tenesmus (rasa tidak tuntas/nyeri saat BAB), serta tinja yang mengandung darah dan lendir yang umumnya berasal dari bakteri seperti Shigella dysenteriae.",
        "saran": "Pengobatan utama untuk disentri adalah dengan penggunaan antibiotik untuk membunuh bakteri penyebabnya. Namun, sangat penting untuk berkonsultasi dengan dokter karena penggunaan jenis antibiotik, dosis, dan interval yang tidak tepat dapat menyebabkan kekambuhan (relaps), resistensi kuman, hingga masalah efek samping.",
        "pencegahan": "Bakteri penyebab disentri sangat mudah ditularkan melalui jalur feses-oral atau melalui konsumsi makanan dan air yang terkontaminasi. Jaga kebersihan diri dan lingkungan secara ketat. Khusus untuk balita dan anak-anak, pastikan asupan gizi yang baik dan pemberian ASI eksklusif untuk memperkuat daya tahan tubuh agar tidak rentan terhadap bakteri.",
        "referensi": "[1] Saputri, G. A. R., dkk. (2023). Penyuluhan Kenali Gejala Dan Cara Penanganan Disentri Pada Sekolah Di SMA Negeri 17 Bandar Lampung. Jurnal Pengabdian Farmasi Malahayati, Vol. 6 No.1.\n[2] Irawan, J., dkk. (2021). Disentri Basiler. Jurnal Medula, Volume 11, Nomor 3.\n[3] Monikawati, T., dkk. Hubungan Ketepatan Penggunaan Antibiotik Dengan Kekambuhan Disentri Pada Pasien Rawat Jalan.\n[4] Kantona, E., dkk. (2024). Faktor Penyebab Kejadian Anak Disentri. Plenary Health: Jurnal Kesehatan Paripurna, Vol. 1 Issue 1."
    },
}